carGenerator:
  generatorSource: live # "live" or "file"
  filesPath: src/main/resources/generator

routeGenerator:
  RoutePathFinder: random # dijkstra or random

testMode: true
workerCount: 3
enableGUI: true
statisticModeActive: false
simulationStep: 1000
mapPath: /Users/mstencel/Studia/Semestr 8/Miss/HiPUTS/data/map.osm
serverAddress: localhost
serverPort: 8081
localHostMode: false
balancingMode: NONE
initialNumberOfCarsPerLane: 0
pauseAfterStep: 200
carViewRange: 300
defaultMaxSpeed: 20.0
maxAcceleration: 2.0
maxDeceleration: 3.5
idmDistanceHeadway: 2.0
idmTimeHeadway: 2.0
idmDelta: 4
junctionSafeTimeDeltaFactor: 1.25
giveWayThreshold: 10
movePermanentThreshold: 50
simulationTimeStep: 1.0
newCars: 15
minCars: 0
ticketActive: false
timeBasedCarGenerationConfigPath: src/main/resources/timeBasedCarGenerationConfig.json
readFromOsmDirectly: true
patchPartitioner:
  partitionerType: hexagon
  carViewRange: 100.0
  borderHandlingStrategy: maxLaneLengthBuffer